// Generated by CoffeeScript 1.9.1
(function() {
  var cit, cit2, citNum, citation;

  citNum = 0;

  citation = (function() {
    function citation(author, date, title, url, number) {
      this.author = author;
      this.date = date;
      this.title = title;
      this.url = url;
      this.number = number != null ? number : citNum;
      citNum += 1;
    }

    citation.prototype.create = function() {
      return this.author + ". (" + this.date + "). " + this.title + " [online]. Available: http://www." + this.url;
    };

    return citation;

  })();

  cit = new citation("James", "Jan 6, 1411", "Some Work", "test.com");

  document.writeln(cit.create());

  cit2 = new citation("Steve", "Jan 13, 1911", "Some New Work", "testing.com");

  document.writeln(cit2.create());

}).call(this);
